'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MuestaDatos

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnMuestaDatos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMuestaDatos As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''vDatos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vDatos As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTitulo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitulo1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFecha1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFecha1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFULLNAME1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFULLNAME1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPRICE1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPRICE1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHIGHDAY1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHIGHDAY1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLOWDAY1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLOWDAY1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCHANGEPCT24HOUR1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCHANGEPCT24HOUR1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTitulo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitulo2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFecha2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFecha2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFULLNAME2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFULLNAME2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPRICE2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPRICE2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHIGHDAY2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHIGHDAY2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLOWDAY2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLOWDAY2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCHANGEPCT24HOUR2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCHANGEPCT24HOUR2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTitulo3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitulo3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFecha3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFecha3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFULLNAME3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFULLNAME3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPRICE3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPRICE3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHIGHDAY3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHIGHDAY3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLOWDAY3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLOWDAY3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCHANGEPCT24HOUR3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCHANGEPCT24HOUR3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTitulo4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitulo4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFecha4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFecha4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFULLNAME4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFULLNAME4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPRICE4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPRICE4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHIGHDAY4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHIGHDAY4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLOWDAY4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLOWDAY4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCHANGEPCT24HOUR4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCHANGEPCT24HOUR4 As Global.System.Web.UI.WebControls.Label
End Class
